### ISSUE TITLE
Question: Only verify signed commits

### ISSUE THREAD

**Issue by gilescope** [Nadock/verified_commits_check#10]
Is it possible to use this action to allow unsigned commits (to allow external contributors),
but if they have signed the commit then check that the git email is the same email associated with the GPG signature?

**Comment by Nadock** [comment]
Hi @gilescope, the purpose of this action is to warn you when pushing unsigned commits to a branch in GitHub. This does not perform any verification of the actual commit signature, that is done by GitHub.

I don't think what you're asking is within the scope of this action so I'm going to close this for now. However, if I've misunderstood what you're asking feel free to follow up.
